shell = "zsh"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zeno]
github = "yuki-yano/zeno.zsh"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.docker-zsh-completion]
github = "greymd/docker-zsh-completion"
apply = ["defer"]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.zsh-vi-man]
github = "TunaCuma/zsh-vi-man"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]
