format = """
$username\
$hostname\
$directory\
$git_branch\
$character
"""

right_format = "$ruby"

[username]
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
ssh_only = false
trim_at = "."
detect_env_vars = []
format = "[@$hostname ]($style)"
disabled = false

[directory]
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "white"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
style = "purple"
[git_metrics]

disabled = false
added_style = "green"
deleted_style = "red"

[ruby]
format = "[$symbol($version )]($style) "
style = "red"

[character]
success_symbol = '[\$](bold green) '
error_symbol = '[\$](bold green) '
